server:
  port: 8080

spring:
  application:
    name: expense-tracker-api

# Firebase configuration
firebase:
  credentials-path: classpath:firebase-adminsdk.json

# JWT configuration
app:
  jwtSecret: expenseTrackerSecretKeyForJWTTokenGenerationThatShouldBeLongEnough
  jwtExpirationMs: 86400000 # 24 hours

# Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Logging
logging:
  level:
    org.example.security: DEBUG
    org.springframework.security: DEBUG