server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:expense-tracker-api}

# Firebase configuration
firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:classpath:firebase-adminsdk.json}
  project-id: ${FIREBASE_PROJECT_ID:expensetrackerapi-e92a6}

# JWT configuration
app:
  jwtSecret: ${JWT_SECRET:expenseTrackerSecretKeyForJWTTokenGenerationThatShouldBeLongEnough}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}

# Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Logging
logging:
  level:
    org.example.security: ${LOG_LEVEL_SECURITY:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    root: ${LOG_LEVEL_ROOT:INFO}