/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

@SpringBootTest
@TestPropertySource(properties = {
    "firebase.credentials-path=classpath:firebase-adminsdk.json"
})
class AppTest {
    @Test 
    void contextLoads() {
        // This test will pass if the Spring context loads successfully
    }
}
